database:
  path: ./.heimdall/cognitive_memory.db
logging:
  level: warn
monitoring:
  enabled: true
  ignore_patterns:
  - .git
  - node_modules
  - __pycache__
  - .pytest_cache
  interval_seconds: 5.0
  target_path: ./.heimdall/docs
project_id: PDF_Editor_6387eb4f
qdrant_url: http://localhost:6333
